export const MODULE_NAME = 'Shadows of Antillia'
export const MODULE_ID = 'revolutionary-antillia'
export const ADVENTURE_STATE_FLAG = 'adventure-state'
export const ZERO_HOUR = -7827019199
export const SECONDS_PER_MINUTE = 60
export const SECONDS_PER_HOUR = 60 * SECONDS_PER_MINUTE
export const SECONDS_PER_DAY = 24 * SECONDS_PER_HOUR
export const SECONDS_PER_WEEK = 7 * SECONDS_PER_DAY
export const UUIDS: Record<string, string> = {
  LOG: 'JournalEntry.bhjmsYTe3uIoHyd9',
  TIMELINE_CH1: 'JournalEntry.bhjmsYTe3uIoHyd9.JournalEntryPage.ONIKQ49Szsbcy0J3',
  TIMELINE_CH2: 'JournalEntry.bhjmsYTe3uIoHyd9.JournalEntryPage.FsVyjdAcsSOumtPz',
  TIMELINE_CH3: 'JournalEntry.bhjmsYTe3uIoHyd9.JournalEntryPage.iHaUyp6MUUfI1wLm',
  TIMELINE_CH4: 'JournalEntry.bhjmsYTe3uIoHyd9.JournalEntryPage.iGrY5plcil5za8FW',
  TIMELINE_CH5: 'JournalEntry.bhjmsYTe3uIoHyd9.JournalEntryPage.T110PO9m3O5trFY2',
  TIMELINE_CH6: 'JournalEntry.bhjmsYTe3uIoHyd9.JournalEntryPage.NB1uM2D0zxEB3KlF',
  INTRO: 'JournalEntry.LF0tUW5xSU8tn8cz.JournalEntryPage.woSCZnMC67RNawLv',
  JOURNAL_ROOT: 'lGxWU3hj8j30VY0P',
  DECRYPTED_INTEL_MESSAGES: 'qqrvDHxpjZn5FYW2',
  ENCRYPTED_INTEL_MESSAGES: 'etmda0JUHwKk4vfl',
  PROPAGANDA: 'B8k0FFzOsEJxrRvg',
  EMPIRES: 'RollTable.pK3FfgibC1HfBefV',
  FORTS: 'RollTable.XleTdybFWP2znvEq',
  FORTS_BRITISH: 'RollTable.oEfVP1A8NzEEPpvA',
  FORTS_DUTCH: 'RollTable.ZCdLm4jmEhR52eKP',
  FORTS_FRENCH: 'RollTable.tfjKw6DW67kDPt2u',
  FORTS_SPANISH: 'RollTable.eBy9oCxCQwjCEoVR',
  ISLANDS: 'RollTable.8RmIebOSZSE2LNVD',
  ISLANDS_BRITISH: 'RollTable.RLWwGvDlIfTwGhlb',
  ISLANDS_DUTCH: 'RollTable.YDhqiw9uorniDCSi',
  ISLANDS_FRENCH: 'RollTable.sF5NjarkOvCw2CVc',
  ISLANDS_SPANISH: 'RollTable.KcRDBi9tljmHlsPt',
  PORTS: 'RollTable.0evF4tpbN2THOwo2',
  PORTS_BRITISH: 'RollTable.lgjwe1CZm74yN1iy',
  PORTS_DUTCH: 'RollTable.KCXH64t3GaYANr2n',
  PORTS_FRENCH: 'RollTable.1G1lRoA0PwKOQ3Q3',
  PORTS_SPANISH: 'RollTable.x9k31Vvq3Jtp4QPS',
  SETTLEMENTS_ANY: 'RollTable.9FmgujKMAVZagL5u',
  SETTLEMENTS_BRITISH: 'RollTable.KDSsuLuEYg2Ewtet',
  SETTLEMENTS_DUTCH: 'RollTable.xeiicDwD3jNHFEz1',
  SETTLEMENTS_FRENCH: 'RollTable.OamCpt8A1vmr0pON',
  SETTLEMENTS_SPANISH: 'RollTable.UugXd5EFP55zrlQN',
  PIRATES: 'RollTable.cJsVMCuw9ch545LX',
  GOVERNORS: 'RollTable.eEVExp6HIqtAc2w9',
  GOVERNORS_BRITISH: 'RollTable.8vhF6q953mMFPfUW',
  GOVERNORS_DUTCH: 'RollTable.6RRExTZxFrMtwZN5',
  GOVERNORS_FRENCH: 'RollTable.78dgsDO5noFLif8J',
  GOVERNORS_SPANISH: 'RollTable.GAL66zLQMb5ArdWa',
  DISEASES_EARLY: 'RollTable.X7OlS669f67d6RIg',
  DISEASES_MID: 'RollTable.evDIkBrY4PZBvGej',
  DISEASES_LATE: 'RollTable.IkSwvdAiCkjrh096',
  JOURNAL_JAMAICA: 'JournalEntry.5x9QoJSjO9XFEazK',
  JOURNAL_BASSE_TERRE: 'JournalEntry.lEN7e6rNj19n4hy2',
  JOURNAL_BASSETERRE: 'JournalEntry.mQgvU9WB3LP7cda4',
  JOURNAL_BRIDGETOWN: 'JournalEntry.UVjbk8JvSPTyYmSk',
  JOURNAL_BORDEAUX: 'JournalEntry.cmC1vP7nKvjgc9TT',
  JOURNAL_CADIZ: 'JournalEntry.mAXf3IQZzkWZyWhr',
  JOURNAL_CAP_FRANCAIS: 'JournalEntry.KaFKJRXB9Zv8MxQd',
  JOURNAL_HAVANA: 'JournalEntry.d2FyewZyG7hc4RgP',
  JOURNAL_KINGSTON: 'JournalEntry.swgzi8mEAgfLJOEk',
  JOURNAL_FORT_CHARLES: 'JournalEntry.swgzi8mEAgfLJOEk.JournalEntryPage.zPBtUYuNIxPTAZ1z',
  JOURNAL_LA_ROCHELLE: 'JournalEntry.v90Kiq308NopiqKa',
  JOURNAL_LE_HAVRE: 'JournalEntry.JgJ7jUEnMsljH1Sd',
  JOURNAL_LONDON: 'JournalEntry.MYQUmzkqzParvGYs',
  JOURNAL_LORIENT: 'JournalEntry.Q8jT8OSpzrLgwrjE',
  JOURNAL_NANTES: 'JournalEntry.N3MR8auFW217jFEN',
  JOURNAL_ST_JOHNS: 'JournalEntry.yIlT64rYoAsSwElE',
  JOURNAL_ST_PIERRE: 'JournalEntry.TnqJdxikuJmgyV2Z',
  JOURNAL_GOVERNOR_JAMAICA: 'JournalEntry.13SE7XeNQmMvODNV.JournalEntryPage.25wbdpX0qlqRyWaV',
  JOURNAL_YELLOW_JACK: 'JournalEntry.IfI5rrlxoD82fxdt.JournalEntryPage.oo0LeabCcf1Vib9w',
  JOURNAL_GRIPPE: 'JournalEntry.IfI5rrlxoD82fxdt.JournalEntryPage.EPDXHrUqpzidD5Uc',
  JOURNAL_FLUX: 'JournalEntry.IfI5rrlxoD82fxdt.JournalEntryPage.keMo9a93hahm40rj',
  JOURNAL_POX: 'JournalEntry.IfI5rrlxoD82fxdt.JournalEntryPage.XLQWptX0pkKVua1C',
  JOURNAL_COUGH: 'JournalEntry.IfI5rrlxoD82fxdt.JournalEntryPage.wuocwzON6uBUBDKg',
  JOURNAL_MEASLES: 'JournalEntry.IfI5rrlxoD82fxdt.JournalEntryPage.OJ8TxsWXxPKvdBK0',
  JOURNAL_BOULOGNE: 'JournalEntry.IfI5rrlxoD82fxdt.JournalEntryPage.2VMr6j2n0ybVy0XF',
  BOTTLE: 'Item.2UylOEF2C19GfRNF',
  MJOLNIR: 'Item.EYNgp4j5ZNKuBgmM',
  TOBACCO: 'Compendium.pirateborg.equipment-gear.Item.evUD546oYBvGyJmb',
  ASH_CARGO: 'Item.lDAchtutyqcPJq1h',
  SUGAR_CARGO: 'Item.Q9clnxDy1Otm00Ed',
  PREMIUM_SKELETON: 'Actor.h7zfo0id60XazmVT',
  PREMIUM_MARROW_CANNON: 'Actor.irqTdv3HtGGBOR2A',
  PREMIUM_DEEP_ONES: 'Actor.XFS1vFzYOZPDOTLd'
}
