export const MODULE_NAME = 'Shadows of Antillia'
export const MODULE_ID = 'revolutionary-antillia'
export const ADVENTURE_STATE_FLAG = 'adventure-state'
export const ZERO_HOUR = -7827019199
export const UUIDS: Record<string, string> = {
  LOG: 'JournalEntry.bhjmsYTe3uIoHyd9',
  TIMELINE: 'JournalEntry.bhjmsYTe3uIoHyd9.JournalEntryPage.ONIKQ49Szsbcy0J3',
  INTRO: 'JournalEntry.LF0tUW5xSU8tn8cz.JournalEntryPage.woSCZnMC67RNawLv',
  JOURNAL_ROOT: 'lGxWU3hj8j30VY0P',
  DECRYPTED_INTEL_MESSAGES: 'qqrvDHxpjZn5FYW2',
  ENCRYPTED_INTEL_MESSAGES: 'etmda0JUHwKk4vfl',
  EMPIRES: 'RollTable.pK3FfgibC1HfBefV',
  FORTS: 'RollTable.XleTdybFWP2znvEq',
  FORTS_BRITISH: 'RollTable.oEfVP1A8NzEEPpvA',
  FORTS_DUTCH: 'RollTable.ZCdLm4jmEhR52eKP',
  FORTS_FRENCH: 'RollTable.tfjKw6DW67kDPt2u',
  FORTS_SPANISH: 'RollTable.eBy9oCxCQwjCEoVR',
  PORTS: 'RollTable.0evF4tpbN2THOwo2',
  PORTS_BRITISH: 'RollTable.lgjwe1CZm74yN1iy',
  PORTS_DUTCH: 'RollTable.KCXH64t3GaYANr2n',
  PORTS_FRENCH: 'RollTable.1G1lRoA0PwKOQ3Q3',
  PORTS_SPANISH: 'RollTable.x9k31Vvq3Jtp4QPS',
  SETTLEMENTS_ANY: 'RollTable.9FmgujKMAVZagL5u',
  SETTLEMENTS_BRITISH: 'RollTable.KDSsuLuEYg2Ewtet',
  SETTLEMENTS_DUTCH: 'RollTable.xeiicDwD3jNHFEz1',
  SETTLEMENTS_FRENCH: 'RollTable.OamCpt8A1vmr0pON',
  SETTLEMENTS_SPANISH: 'RollTable.UugXd5EFP55zrlQN',
  PIRATES: 'RollTable.cJsVMCuw9ch545LX',
  GOVERNORS: 'RollTable.eEVExp6HIqtAc2w9',
  GOVERNORS_BRITISH: 'RollTable.8vhF6q953mMFPfUW',
  GOVERNORS_DUTCH: 'RollTable.6RRExTZxFrMtwZN5',
  GOVERNORS_FRENCH: 'RollTable.78dgsDO5noFLif8J',
  GOVERNORS_SPANISH: 'RollTable.GAL66zLQMb5ArdWa',
  DISEASES_EARLY: 'RollTable.X7OlS669f67d6RIg',
  DISEASES_MID: 'RollTable.evDIkBrY4PZBvGej',
  DISEASES_LATE: 'RollTable.IkSwvdAiCkjrh096',
  JOURNAL_BASSE_TERRE: 'JournalEntry.lEN7e6rNj19n4hy2',
  JOURNAL_BASSETERRE: 'JournalEntry.mQgvU9WB3LP7cda4',
  JOURNAL_BRIDGETOWN: 'JournalEntry.UVjbk8JvSPTyYmSk',
  JOURNAL_BORDEAUX: 'JournalEntry.cmC1vP7nKvjgc9TT',
  JOURNAL_CADIZ: 'JournalEntry.mAXf3IQZzkWZyWhr',
  JOURNAL_CAP_FRANCAIS: 'JournalEntry.KaFKJRXB9Zv8MxQd',
  JOURNAL_HAVANA: 'JournalEntry.d2FyewZyG7hc4RgP',
  JOURNAL_KINGSTON: 'JournalEntry.swgzi8mEAgfLJOEk',
  JOURNAL_FORT_CHARLES: 'JournalEntry.swgzi8mEAgfLJOEk.JournalEntryPage.zPBtUYuNIxPTAZ1z',
  JOURNAL_LA_ROCHELLE: 'JournalEntry.v90Kiq308NopiqKa',
  JOURNAL_LE_HAVRE: 'JournalEntry.JgJ7jUEnMsljH1Sd',
  JOURNAL_LONDON: 'JournalEntry.MYQUmzkqzParvGYs',
  JOURNAL_LORIENT: 'JournalEntry.Q8jT8OSpzrLgwrjE',
  JOURNAL_NANTES: 'JournalEntry.N3MR8auFW217jFEN',
  JOURNAL_ST_JOHNS: 'JournalEntry.yIlT64rYoAsSwElE',
  JOURNAL_ST_PIERRE: 'JournalEntry.TnqJdxikuJmgyV2Z',
  JOURNAL_GOVERNOR_JAMAICA: 'JournalEntry.13SE7XeNQmMvODNV.JournalEntryPage.25wbdpX0qlqRyWaV',
  JOURNAL_YELLOW_JACK: 'JournalEntry.IfI5rrlxoD82fxdt.JournalEntryPage.oo0LeabCcf1Vib9w',
  BOTTLE: 'Item.2UylOEF2C19GfRNF',
  ASH_CARGO: 'Item.lDAchtutyqcPJq1h',
  SUGAR_CARGO: 'Item.Q9clnxDy1Otm00Ed'
}
